- hosts: example

  tasks:
    - assert:
        that:
          - num == 1
          - num <= 2
      vars:
        num: 1

    - assert:
        that:
          - known is defined
          - unknown is not defined
          - not unknown is defined
          - known is defined and unknown is not defined
          - not known is not defined
          - known is defined or known is not defined
          - not (known is defined and known is not defined)
      vars:
        known: true

    - assert:
        that:
          # equivalence of variable and variable
          - some_string == assert_string

          # equivalence of variable and string
          - some_string == 'MY NAME IS ME'

          # equivalence of variable and variable expansion
          - some_string == '{{ assert_string }}'

          # equivalence of string and string : not use variables ( double quotes for YAML syntax not for ansible )
          - "'MY NAME IS ME' == 'MY NAME IS ME'"
      vars:
        some_string: MY NAME IS ME
        assert_string: MY NAME IS ME

    - command: /bin/true
      register: true_result
      changed_when: no

    - command: /bin/true
      register: changed_result 
      changed_when: yes

    - command: /bin/false
      register: false_result 
      ignore_errors: yes

    - assert:
        that:
          - true_result is succeeded
          - true_result is not failed
          - changed_result is changed
          - false_result is failed
          - false_result is not succeeded

    - name: Assert string in string
      assert:
        that:
          - "'string' in 'Here is some string'"

    - name: set fruits and vegetables
      set_fact:
        fruits:
          - apple
          - banana
        vegetables:
          - asparagus
          - broccoli 
   
    - name: Assert string in array
      assert:
        that:
          - "'banana' in fruits"

    - name: Assert not string in array
      assert:
        that:
          - "'cherry' not in fruits"

    - name: Assert equivalence array and array
      assert:
        that:
          - fruits == fruits

    - name: Assert difference array between another array
      assert:
        that:
          - fruits != vegetables
