- hosts: example
  vars:
    num: 1
    some_string: MY NAME IS ME
    assert_string: MY NAME IS ME

  tasks:
    - assert:
        that:
          - num == 1
          - num <= 2

    - assert:
        that:
          - num is defined
          - unknown is not defined
          - not unknown is defined

    - assert:
        that:
          # equivalence of variable and variable
          - some_string == assert_string

          # equivalence of variable and string
          - some_string == 'MY NAME IS ME'

          # equivalence of variable and variable expansion
          - some_string == '{{ assert_string }}'

          # equivalence of string and string : not use variables ( double quotes for YAML syntax not for ansible )
          - "'MY NAME IS ME' == 'MY NAME IS ME'"

    - command: /bin/true
      register: true_result 

    - command: /bin/true
      register: changed_result 
      changed_when: yes

    - command: /bin/false
      register: false_result 

    - assert:
        that:
          - true_result is succeeded
          - changed_result is changed
          - false_result is failed

