# https://docs.ansible.com/ansible/devel/user_guide/playbooks_intro.html#handlers-running-operations-on-change
---
- hosts: example

<<<<<<< HEAD
  # FIXME : not work
  handlers:
    - debug:
        msg: i am the handler
        listen: hook

  tasks:
    - debug:
      notify: hook
=======
  handlers:
    - debug:
        msg: i am the handler
      listen: hook to me
    - debug:
        msg: you are the handler
      listen: hook to you

  tasks:
    - shell: ls # debug module does not notify to handler, so use some other module
<<<<<<< HEAD
      notify: "hook"
>>>>>>> Add ansible handler playbook
=======
      notify: hook to me
    - shell: ls
      notify: hook to me  # hook twice but run handler once
    - shell: ls
      notify: hook to you
>>>>>>> Fix ansible handler playbook work

