# https://docs.ansible.com/ansible/devel/user_guide/playbooks_intro.html#handlers-running-operations-on-change
---
- hosts: example

  handlers:
    - debug:
        msg: i am the handler
      listen: hook to me
    - debug:
        msg: you are the handler
      listen: hook to you
    - debug:
        msg: he is the handler
      listen: hook to him

  tasks:
    - debug:
        msg: message
      changed_when: true
      notify: hook to me
    - debug: 
        msg: try to hook to me
      changed_when: true
      notify: hook to me  # hook twice but run handler once
    - debug:
        msg: try to hook to you
      changed_when: true
      notify: hook to you
    - debug:
        msg: try to hook to him
      changed_when: false # no changed no hook
      notify: hook to him
