# https://docs.ansible.com/ansible/devel/user_guide/playbooks_intro.html#handlers-running-operations-on-change
---
- hosts: example

<<<<<<< HEAD
  # FIXME : not work
  handlers:
    - debug:
        msg: i am the handler
        listen: hook

  tasks:
    - debug:
      notify: hook
=======
  handlers:
    - debug:
        msg: i am the handler
      listen: "hook"

  tasks:
    - shell: ls # debug module does not notify to handler, so use some other module
      notify: "hook"
>>>>>>> Add ansible handler playbook

