# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html

- hosts: example
  tasks:

    # hello
    # ansible
    # world
    - debug:
        msg: "{{ item }}"
      with_list:
        - hello
        - ansible
        - world

    - set_fact:
        messages: ["hello", "ansible", "world"]

    # hello
    # ansible
    # world
    - debug:
        msg: "{{ item }}"
      with_items: "{{ messages }}"

    # 0 - hello
    # 1 - ansible
    # 2 - world
    - debug:
        msg: "{{ item.0 }} - {{ item.1 }}"
      with_indexed_items: "{{ messages }}"

    # hello
    # ansible
    # world
    - debug:
        msg: "{{ item }}"
      with_flattened: ["hello", ["ansible", [["world"]]]]

    # hello1 ansible1 world1
    # hello2 ansible2 world2
    # hello3 ansible3 world3
    - debug:
        msg: "{{ item.0 }} {{ item.1 }} {{ item.2 }}"
      with_together:
        - ["hello1", "hello2", "hello3"]
        - ["ansible1", "ansible2", "ansible3"]
        - ["world1", "world2", "world3"]

    # a hello
    # b ansible
    # c world
    - debug:
        msg: "{{ item.key }} {{ item.value}}"
      with_dict: {a: "hello", b: "ansible", c: "world" }

    # 03
    # 06
    # 09
    - debug:
        msg: "{{ item }}"
      with_sequence: start=3 end=9 stride=3 format=%02x

    # name : Alice , like : Apple
    # name : Alice , like : Microsoft
    # name : Bob , like : Soccer
    # name : Bob , like : Basket
    - debug:
        msg: "name : {{ item.0.name }} , like : {{ item.1 }}"
      with_subelements: 
        - [{ name: "Alice", sex: "female", likes: ["Apple", "Microsoft"] }, { name: "Bob", sex: "male", likes: ["Soccer", "Basket"] }]
        - likes
      tags: with_subelements

    # hello ansible strong
    # hello world zero 
    # bye ansible strong
    # bye world zero
    # hello ansible strong 
    # hello world zero
    # bye ansible strong
    # bye world zero
    - debug:
        msg: "{{ item.0 }} {{ item.1 }}"
      with_nested:
        - ["hello", "bye"]
        - ["ansible", "world"]
        - ["strong", "zero"]
      tags: with_nested

    # hello or ansible or world
    - debug:
        msg: "{{ item }}"
      with_random_choice: ["hello", "ansible", "world"]
      tags: with_random_choice
