- hosts: example
  tasks:

    # hello
    # ansible
    # world
    - debug:
        msg: "{{ item }}"
      with_list:
        - hello
        - ansible
        - world

    - set_fact:
        messages: ["hello", "ansible", "world"]

    # hello
    # ansible
    # world
    - debug:
        msg: "{{ item }}"
      with_items: "{{ messages }}"

    # 0 - hello
    # 1 - ansible
    # 2 - world
    - debug:
        msg: "{{ item.0 }} - {{ item.1 }}"
      with_indexed_items: "{{ messages }}"

    # hello
    # ansible
    # world
    - debug:
        msg: "{{ item }}"
      with_flattened: ["hello", ["ansible", [["world"]]]]

    # hello1 ansible1 world1
    # hello2 ansible2 world2
    # hello3 ansible3 world3
    - debug:
        msg: "{{ item.0 }} {{ item.1 }} {{ item.2 }}"
      with_together:
        - ["hello1", "hello2", "hello3"]
        - ["ansible1", "ansible2", "ansible3"]
        - ["world1", "world2", "world3"]

    # a hello
    # b ansible
    # c world
    - debug:
        msg: "{{ item.key }} {{ item.value}}"
      with_dict: {a: "hello", b: "ansible", c: "world" }
