# Intro to Playbooks
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html#about-playbooks

# You can specify multiple "Play" in one playbook

# This is first Play
# You can specify multiple hosts and tasks on one Play
- hosts:
    - group1
    - group2
  # Tasks have many steps with modules
  tasks:
    # The first step of tasks
    - name: debug message
      debug: # Specify Module
        msg: # Module option

    # The second step of tasks
    - name:
      shell: echo OK
      changed_when: no # directive for this task ( Not Module option )

# This is second Play
- hosts:
    - group2
    - group3
  tasks:
    - name: Execute shell and echo unixtime millisecond
      shell: date +%s%N
      register: shell_result
      changed_when: no

    - name: Show shell script result
      debug:
        var: shell_result

    # First task
    - name: debug alice variable
      debug:
        var: alice # this is "debug module" option
      vars: # this is directive ( set variables in only this task )
        alice: My name is alice

    - name: touch file
      file:
        path: touch.txt
        state: touch
