- hosts: localhost
  tasks:
    - name: add register with execute debug module
      debug:
        msg: add debug module result into debugged_register variable
      register: debugged_register

    # "msg": {
    #     "changed": false,
    #     "failed": false,
    #     "msg": "add register of debug module result!"
    # }
    - name: show register variable values set by execute debug module
      debug:
        msg: "{{ debugged_register }}"

    - name: skip execute task but register got variable
      debug:
        msg: add register of debug module result!
      register: not_executed_module_register
      when: false

    #  "msg": {
    #      "changed": false,
    #      "skip_reason": "Conditional result was False",
    #      "skipped": true
    #  }
    - name: show not_executed_module_register variable
      debug:
        msg: "{{ not_executed_module_register }}"

    - assert:
        that:
          - not_executed_module_register is defined
          - not_executed_module_register is not changed
          - not_executed_module_register is skipped
 
