- hosts:
    - example
  tasks:
    - name: Execute shell script
      script: files/echo.sh arg1 arg2
      # You can pass script ENV like...
      # SOME_ENV="some env value" echo.sh
      environment:
        SOME_ENV: some env value
      changed_when: no
      register: script_module_result

    - name: Show script module executed result
      debug:
        var: script_module_result

    - name: Show shell script stdout
      debug:
        msg: "shell script stdout is ... {{ script_module_result.stdout }}"

    - name: Show shell script stdout lines
      debug:
        msg: "{{ item }}"
      with_items: "{{ script_module_result.stdout_lines }}"

    - name: Execute local python script
      script: files/print.py
      args:
        executable: python
      changed_when: no
      register: python_script_result
 
    - name: Show python script executed result
      debug:
        var: python_script_result
