- hosts: localhost
  tasks:
    - file:
        path: some_dir
        state: directory

    - stat:
        path: some_dir
      register: dir

    - debug:
        msg: "{{ dir }}"

    - debug:
        msg: directory exists
      when: dir.stat.exists

    - file:
        path: some_dir
        state: absent
