- hosts: localhost
  tasks:
    - file:
        path: hello-ansible-world
        state: directory

    - stat:
        path: hello-ansible-world
      register: dir

    - debug:
        msg: "{{ dir }}"

    - debug:
        msg: directory exists
      when: dir.stat.exists
