- hosts: localhost
  tasks:
    - set_fact:
        alice:
          name: Alice
          job: not engineer
          age: 98
          evil_mind: # empty string 
          changed: true
          success: "true"
          failure: false
          kicked: true

    # present string evaluate as true
    - debug:
        msg: "Alice's name is {{ alice.name }}"
      when:
        - alice.name

    # not present string evaluate as false
    - debug:
        msg: "Alice is not evil"
      when:
        - not alice.evil_mind

    # skipped
    - debug:
        msg: "not exists variable exists why ?"
      when:
        - not_defined_variable is defined 
        - not_defined_variable # not evaluate

    # skipped
    - debug:
        msg: "not exists variable exists why ?"
      when:
        - not_defined_variable is defined and not_defined_variable

    # You can use "is succeeded" conditional syntax
    # because alice dictionary has "success" key and boolean value
    - debug:
        msg: "Alice has succeeded as not enginner"
      when:
        - alice is succeeded

    - debug:
        msg: "Alice is not evil"
      when:
        - not alice.evil_mind

    # You can use "is changed" conditional syntax
    # because alice dictionary has "changed" key and boolean value
    - debug:
        msg: "Alice was changed"
      when:
        - alice is changed

    # You can use "is failed" conditional syntax
    # because alice dictionary has "failure" key and boolean value
    - debug:
        msg: "Alice was not failed to swimming"
      when:
        - alice is not failed

    # You can not use some new original conditional syntax
    #  The conditional check 'alice is kicked' failed. The error was: template error while templating string: no test named 'kicked'
    # - debug:
    #    msg: "Alice has kicked from chat room"
    #  when:
    #    - alice is kicked

    # skipped
    - debug:
        msg: "Can you see unknown information of Alice?"
      when:
        - alice.not_defined_info is defined
